services:
  - type: web
    name: smartbuilding-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_PATH
        value: /opt/render/project/src/smartbuilding.db
